name: CI
on:
  workflow_dispatch:  
  push:
    tags:
      - v*
env:
  ASAN_OPTIONS: handle_segv=0:detect_leaks=1:detect_stack_use_after_return=0:disable_coredump=0:abort_on_error=1
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0
jobs:
  build-asan:      
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: ubuntu-latest
            prefix: linux-x64
            out-dir: out
          - host: macos-latest
            prefix: mac
            out-dir: xcodebuild
          - host: windows-latest
            prefix: win
            out-dir: out
    name: Build ASan-enabled Dart runtime
    runs-on: ${{ matrix.host }}
    steps:
      - name: Print Clang version
        run: clang --version

      - uses: actions/checkout@v3
      - name: Get dependencies
        if: runner.os != 'Windows'
        working-directory: ${{ env.HOME }}
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$PWD/depot_tools" >> $GITHUB_PATH      
      
      - name: Get dependencies (Windows)
        if: runner.os == 'Windows'
        working-directory: ${{ env.HOME }}
        run: |
          curl -L https://storage.googleapis.com/chrome-infra/depot_tools.zip -o depot_tools.zip
          7z x depot_tools.zip -odepot_tools
          echo "$(pwd)/depot_tools" >> $env:GITHUB_PATH

      - name: Fetch Dart SDK
        run: fetch dart
      
      - name: Build runtime
        run: python3 ./tools/build.py --no-goma --mode release --arch x64 --sanitizer asan runtime
        working-directory: sdk
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dart-asan-${{ runner.os }}
          path: sdk/${{ matrix.out-dir }}/ReleaseASANX64/exe.stripped
        
